services:
  db:
    image: hub.hamdocker.ir/postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgresTest/.env
    environment:
      DB_NAME: testdb
      DB_USER: ashkantariverdi
      DB_PASSWORD: ashkan82
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 postgresTest.wsgi:application
    volumes:
      - .:/app
    env_file:
      - ./postgresTest/.env
    environment:
      DEBUG: 'True'
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
